### ISSUE TITLE
`workspace_client` parameter doesn't exist before Varnish 4.0

### ISSUE THREAD

**Issue by ocean90** [ttssdev/appflow-playbooks#4]
#2 added the `workspace_client` parameter to `roles/web/templates/lib/systemd/system/varnish.service.j2`. Now if you're still using Varnish 3.x the service will fail to start:

```
jdoe@compute-01 ~ % sudo service varnish restart
 * Stopping HTTP accelerator varnishd                                                                                                          [fail]
 * Starting HTTP accelerator varnishd                                                                                                          [fail]
Error:
Unknown parameter "workspace_client".
```

The parameter should probably be wrapped with a`{% if conf_varnish_version >= 40 %}` check or something.

**Comment by 89luca89** [comment]
Varnish 3 is EOL
https://ma.ttias.be/varnish-cache-3-0-is-end-of-life/

Consider upgrading to a newer version (we will remove support for 3 in playbooks soon)
