### ISSUE TITLE
Are WP_HOME and WP_SITEURL still necessarily tied to http?

### ISSUE THREAD

**Issue by neverything** [ttssdev/appflow-playbooks#6]
@ivomarino is `http://` still necessary for haproxy or was it varnish in the WP constants `WP_HOME` and `WP_SITEURL`?

https://github.com/ttssdev/appflow-playbooks/blob/b3aa85bfb199743755659875fd3e8f1937bae573/roles/web/templates/wp_bedrock/env.j2#L17-L20

**Comment by ivomarino** [comment]
@neverything you want to set `https://` here?

**Comment by neverything** [comment]
@ivomarino yes, as otherwise the sites sometimes give out mixed content warnings.
