### ISSUE TITLE
Allow server to connect to itself without credentials if basic auth is enabled

### ISSUE THREAD

**Issue by ocean90** [ttssdev/appflow-playbooks#8]
https://github.com/ttssdev/appflow-playbooks/blob/b3aa85bfb199743755659875fd3e8f1937bae573/roles/web/templates/wp_bedrock/htaccess.j2#L8-L15

This should include a whitelist of server IPs which don't require the credentials.

Example:
```
AuthType Basic
AuthName "Protectd"
AuthUserFile /etc/apache2/.htpasswd
Order allow,deny
Allow from 127.0.0.1
Allow from ::1
Allow from <server-ip>
Satisfy Any
```

**Comment by ivomarino** [comment]
@ocean90 https://github.com/ttssdev/appflow-playbooks/pull/13 closes this?
